### ISSUE TITLE
Wrongly generated URLs

### ISSUE THREAD

**Issue by fluential** [vialink/viacrypt#3]
My version cloned yesterday to be wrongly generating urls which looks like this:
http:foor.bar.com/#<KEY>

nevertheless when I am accessing foor.bar.com/#<KEY> I am getting just empty window ready to "save" a message, no other information is displayed: like actual message or a warning that his message had been read already. Ideas?

**Comment by jansegre** [comment]
What have you configured on your config.js for the baseurl?

The default configuration is `cfg.baseurl = '//viacry.pt';`.

Note that it must start with `//`. For trying it locally `//localhost:8001` is the way to go.

**Comment by fluential** [comment]
Right, my mistake, thanks for the great software!

**Comment by ghost** [comment]
I am trying to deploy the application in my Linux AMI server and the base URL for Single-use URL only comes as the 127.0.0.1 but not as the server IP.  I have tried to configure the settings in default.js from 
`cfg.http = {
	listen: '127.0.0.1',
	port: 8001
};` to `cfg.http = {
	listen: 'xx.xxx.xxx.xxx',
	port: 8001
};`  This causes an error with grunt build something like this 

```
Waiting...Server running at xx.xxx.xxx.xxx:8001
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 52.0.10.94:8001
    at Server.setupListenHandle [as _listen2] (net.js:1269:19)
    at listenInCluster (net.js:1334:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1460:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
>> application exited with code 1
```
Am I doing anything wrong ?

**Comment by jansegre** [comment]
@ashish308 I'd guess that the address you're trying to listen on (`xx.xxx.xxx.xxx`) is not actually on the host, but rather on the gateway, and the host has an internal address (`172.yyy.yyy.yy` for example) that gets NAT'ed by the gateway to the public xx... address.

You could run something like `ip a` (or ìp -4 a` for only IPv4) to see all addresses available on the host (which you could use for the listen). Alternatively it is possible to listen on the _any address_ which is `0.0.0.0`.

However given all that, I recommend listening on `127.0.0.1` and using a reverse proxy (like nginx) to expose the service. This is because web servers like nginx are more robust in handling connections with internet clients, specially with slow clients.

**Comment by ghost** [comment]
thank you for the great explanation. I was able to deploy successfully.
